# -*- coding: utf-8 -*-
"""my_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbtpe5DnAKMeXVuaMayWiEjb4c0Y3J9a
"""

import pandas as pd

# Rebuild the dataset
data = {
    'OrderID': [1001, 1002, 1003, 1004, 1005, 1006],
    'Customer': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Emma'],
    'Product': ['Laptop', 'Phone', 'Shoes', 'Headphones', 'Jacket', 'Book'],
    'Category': ['Electronics', 'Electronics', 'Fashion', 'Electronics', 'Fashion', 'Books'],
    'Quantity': [1, 2, 3, 1, 2, 4],
    'Price': [1200, 800, 60, 150, 90, 20],
    'OrderDate': pd.to_datetime(['2025-01-05','2025-01-07','2025-01-08','2025-01-10','2025-01-12','2025-01-15']),
    'City': ['London','Paris','Berlin','London','Madrid','Rome']
}

df = pd.DataFrame(data)

# Preview
print(df)

df['Revenue'] = df['Quantity'] * df['Price']
print(df[['OrderID','Product','Quantity','Price','Revenue']])

print(df.groupby('Category')['Revenue'].sum())

product_sales = df.groupby('Product')['Quantity'].sum()
print(product_sales)
print("Top product:", product_sales.idxmax(), "with", product_sales.max(), "units")

daily_revenue = df.groupby('OrderDate')['Revenue'].sum()
print(daily_revenue)

city_revenue = df.groupby('City')['Revenue'].sum()
print(city_revenue)

import matplotlib.pyplot as plt

# Revenue trend
daily_revenue.plot(kind='line', marker='o', title='Revenue Trend Over Time')
plt.show()

# Revenue by city
city_revenue.plot(kind='bar', title='Revenue by City', color='skyblue')
plt.show()











